# Generated by Django 5.2.6 on 2025-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default11.jpg', upload_to='profile_pics'),
        ),
    ]
